// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_cva6_minimal_top.h for the primary calling header

#ifndef VERILATED_VTB_CVA6_MINIMAL_TOP___024ROOT_H_
#define VERILATED_VTB_CVA6_MINIMAL_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_cva6_minimal_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_cva6_minimal_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_cva6_minimal_top__DOT__sys_clock;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__aresetn;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__sys_reset_n;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__led;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__led_prev;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__uart_rx_byte;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__uart_bit_index;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__uart_rx_state;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__prev_state;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__reset_sync;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_req;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_req__VforceRd;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_req__VforceEn;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_req__VforceVal;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_we;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_we__VforceRd;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_we__VforceEn;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_we__VforceVal;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_be;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_be__VforceRd;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_be__VforceEn;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_be__VforceVal;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__ram_select;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__uart_select;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__hbm3_select;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__hbm3_cfg_select;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__hbm3_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__hbm3_valid__VforceRd;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__hbm3_valid__VforceEn;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__hbm3_valid__VforceVal;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT____Vcellinp__u_data_ram__req;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awid;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awlen;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awsize;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awburst;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awlock;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awcache;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awprot;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awqos;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awregion;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awvalid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awready;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_wvalid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_wready;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_bvalid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_bready;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arid;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arlen;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arsize;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arburst;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arlock;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arcache;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arprot;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arqos;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arregion;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arvalid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_arready;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_rid;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_rresp;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_rvalid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_rready;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_psel;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_penable;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_pwrite;
    };
    struct {
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_pready;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_state;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT____Vcellinp__u_mem_to_axi_bridge__mem_req;
        CData/*4:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__fifo_wr_ptr;
        CData/*4:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__fifo_rd_ptr;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__fifo_full;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__fifo_empty;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__tx_state;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__bit_index;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__tx_data;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__tx_active;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__tx_line;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_mem_to_axi_bridge__DOT__state;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_mem_to_axi_bridge__DOT__next_state;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_mem_to_axi_bridge__DOT__transaction_id;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmd_wr_en;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmd_wr_ready;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__queue_full;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__rd_queue_rd_en;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__rd_queue_empty;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__rd_queue_full;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__qtype;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_valid;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_bank;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_data_mask;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_burst_len;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_channel;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_bank_group;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_id;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdprocessor_to_cmdmngr_cmd_ready;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdprocessor_to_cmdmngr_command_processed;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_write_data_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdprocessor_to_cmdmngr_read_data_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmgr_refctrl_refresh_cmd_valid;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmgr_refctrl_refresh_per_bank;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmgr_refctrl_refresh_all_banks;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__refctrl_cmdmgr_ref_done;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdpr_to_refctrl_cmd_proc_busy;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdpr_to_refctrl_ref_cmd_ready;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdpr_to_dfi_wrdata_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_cmdpr_rddata_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_cmdpr_cmd_done;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_bank;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_cs_n;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_ras_n;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_cas_n;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_we_n;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_act_n;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_wrdata_en;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__phy_to_dfi_rddata_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__phy_to_dfi_rddata_dnv;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT____Vcellout__u_command_manager__cmdmngr_to_cmdprocessor_cmd_type;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_ctrl_en;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_refresh_en;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_reorder_en;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_timing_trcd;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_timing_trp;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_timing_tras;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_timing_trc;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_timing_wl;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_timing_rl;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__apb_state;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__write_enable;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__read_enable;
    };
    struct {
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__access_error;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT____VdfgTmp_ha99f8a08__0;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__aw_state;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__aw_state_next;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__aw_state_prev;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__ar_state;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__ar_state_next;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__bresp_pending;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__wr_addr_error;
        CData/*4:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__outstanding_reads;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rdata_pending;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__clear_trans_req;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__clear_trans_id;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_buf_wr_ptr;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_buf_rd_ptr;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk1__DOT__addr_valid_1;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk4__DOT__addr_valid_r;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk9__DOT__special_response_found;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__waiting_for_command;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__waiting_for_data;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__cmd_assembly_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__assembly_error;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__stored_qtype;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__wr_ptr;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_ptr;
        CData/*4:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__valid_count;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__dispatched_entry_idx;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__entry_dispatched;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__dispatched_to_refresh;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue_wr_ptr;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue_rd_ptr;
        CData/*4:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue_count;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__selected_entry_idx;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__dispatch_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__dispatch_to_refresh;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__cmd_dispatched;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__cmd_written;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__cmd_completed;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__bit_cmd_processed;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__temp_remaining;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__current_idx;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__unnamedblk3__DOT__incoming_cmd_type;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__unnamedblk3__DOT__first_bit_idx;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__unnamedblk3__DOT__found_first_bit;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__unnamedblk5__DOT__next_bit_idx;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__unnamedblk5__DOT__remaining;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk2__DOT__unnamedblk5__DOT__found_next_bit;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk18__DOT__data_written;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__unnamedblk18__DOT__data_read;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__state;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__next_state;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__refctrl_cmdpr_ref_cmd_valid_reg;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__refctrl_cmdpr_ref_bank_reg;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__refctrl_cmdpr_ref_all_banks_reg;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__auto_refresh_req;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__current_bank;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_source;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_source;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__outstanding_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__outstanding_source;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__outstanding_is_write;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__refresh_pending;
    };
    struct {
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_cmd_type;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_cmd_type;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_cmd_channel;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_cmd_channel;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_cmd_bank_group;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_cmd_bank_group;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_cmd_bank;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_cmd_bank;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_cmd_burst_len;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_cmd_burst_len;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_cmd_id;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_cmd_id;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_tRCD;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_tRCD;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_tRP;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_tRP;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_tRAS;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_tRAS;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_tRC;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_tRC;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT____VdfgTmp_hdca86341__0;
        VlWide<24>/*767:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__bank_state;
        VlWide<64>/*2047:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__timing_counter_tRCD;
        VlWide<64>/*2047:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__timing_counter_tRAS;
        VlWide<64>/*2047:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__timing_counter_tRP;
        VlWide<64>/*2047:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__timing_counter_tRC;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__cmd_queue_level;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__cmd_queue_full;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__cmd_queue_empty;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__cmd_sched_issue;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__cmd_sched_issue_r;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__timing_ready;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__unnamedblk7__DOT__enqueue_cmd;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__unnamedblk7__DOT__dequeue_cmd;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf6719eb6__0;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf6719eb6__1;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf6719eb6__2;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf6719eb6__3;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf0b8bd5e__0;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf0b8bd5e__1;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf0b8bd5e__2;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf0b8bd5e__3;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h15960473__0;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf0b8bd5e__4;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h4d2a5416__0;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h4b4fb577__0;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h55f848dd__0;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h3fd3f072__0;
        CData/*1:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h40a184d2__0;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h502089cb__0;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h3ffc598f__0;
        CData/*7:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h5a068f74__0;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h8d77490c__0;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__cmd_is_read;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__cmd_is_write;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__cmd_is_activate;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_cmd_bank;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_cmd_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_data_hold_valid;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_valid_reg;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_bank_reg;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__dq_oe;
        CData/*4:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__rd_latency_counter;
        CData/*3:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__rd_bank_reg;
    };
    struct {
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__data_capture_valid;
        CData/*2:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__state;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__is_addi;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__is_sw;
        CData/*0:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__is_bne;
        CData/*3:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__reset_sync;
        CData/*1:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__apb_state;
        CData/*3:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_mem_to_axi_bridge__DOT__transaction_id;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__apb_pready;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__axi_awready;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__axi_wready;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__bresp_pending;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__axi_arready;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v0;
        CData/*3:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v0;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v0;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v1;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v2;
        CData/*7:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v2;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v3;
        CData/*2:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v3;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v4;
        CData/*1:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v4;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v5;
        CData/*0:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v5;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v6;
        CData/*3:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v6;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v7;
        CData/*2:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v7;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v8;
        CData/*3:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v8;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v9;
        CData/*3:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v9;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v10;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v11;
        CData/*1:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v11;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v11;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v12;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v13;
        CData/*1:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v13;
        CData/*4:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__outstanding_reads;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v14;
        CData/*2:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v0;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v0;
        CData/*2:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_buf_rd_ptr;
        CData/*2:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v1;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v1;
        CData/*2:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v2;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v2;
        CData/*2:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v3;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v3;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v4;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rdata_pending;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_write_data_valid;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue__v0;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue__v0;
        CData/*3:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue_rd_ptr;
        CData/*4:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue_count;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue__v1;
        CData/*3:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__current_bank;
        CData/*2:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__state;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_valid;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_valid;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_source;
    };
    struct {
        CData/*3:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__cmd_queue_level;
        CData/*3:0*/ __Vdlyvdim0__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__active_row__v0;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__active_row__v0;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__active_row__v1;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_cmd_valid;
        CData/*0:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_data_hold_valid;
        CData/*0:0*/ __Vdlyvset__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__memory_array__v0;
        CData/*4:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__rd_latency_counter;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_cva6_minimal_top__DOT__sys_clock__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_cva6_minimal_top__DOT__dut__DOT__aresetn__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__uart_bit_counter;
        SData/*11:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_paddr;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__clk_count;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_row;
        SData/*9:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_col;
        SData/*8:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_wrdata_mask;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_timing_trfc;
        SData/*11:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__unnamedblk2__DOT__ch_offset;
        SData/*11:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__unnamedblk3__DOT__ch_offset;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_valid;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_scanning_active;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_all_banks;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_valid;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_is_activate;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_is_read;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_is_write;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_is_refresh;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_is_sre;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_is_srx;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_needs_write_data;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_routes_to_refresh;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_all_banks;
        SData/*14:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_cmd_row;
        SData/*14:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_cmd_row;
        SData/*9:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_cmd_col;
        SData/*9:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_cmd_col;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage1_tRFC;
        SData/*15:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_processor__DOT__stage0_tRFC;
        VlWide<120>/*3839:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__bank_open_row;
        VlWide<128>/*4095:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__timing_counter_tRFC;
        SData/*8:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__ecc_check_bits_wr;
        SData/*14:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hcc1cbcd7__0;
        SData/*14:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_hf96993eb__0;
        SData/*14:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h48934799__0;
        SData/*9:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h65087b3b__0;
        SData/*8:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__ecc_captured;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__cycle_count;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__led_toggle_count;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__instr_count;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__fetched_instr;
        IData/*31:0*/ tb_cva6_minimal_top__DOT____Vlvbound_hc83af77f__1;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_addr;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_addr__VforceRd;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_addr__VforceEn;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_addr__VforceVal;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_wdata;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_wdata__VforceRd;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_wdata__VforceEn;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_wdata__VforceVal;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_rdata;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_rdata__VforceRd;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_rdata__VforceEn;
    };
    struct {
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__data_rdata__VforceVal;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__rom_rdata;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__ram_rdata;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__led_reg;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__hbm3_rdata;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awaddr;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_awuser;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_wuser;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_araddr;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_aruser;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_pwdata;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_prdata;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__apb_rdata_reg;
        IData/*17:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_address;
        VlWide<3>/*71:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_phy_wrdata;
        VlWide<5>/*136:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT____Vcellout__u_hbm3_phy__phy_to_dfi_rddata;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__read_data;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__unnamedblk2__DOT__ch_num;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__unnamedblk3__DOT__ch_num;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk4__DOT__alloc_idx;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk4__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__unnamedblk9__DOT__unnamedblk11__DOT__i;
        VlWide<4>/*127:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__cmd_assembled;
        IData/*19:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_refresh_controller__DOT__trefi_counter;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__unnamedblk3__DOT__ch;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__unnamedblk1__DOT__ch;
        IData/*17:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_cmd_row;
        IData/*17:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_cmd_col;
        VlWide<5>/*136:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_data_hold;
        VlWide<5>/*136:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_data_reg;
        IData/*17:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_row_reg;
        IData/*17:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__wr_col_reg;
        IData/*17:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__rd_row_reg;
        IData/*17:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__rd_col_reg;
        VlWide<4>/*127:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__dq_captured;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__k;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__pc;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__imm_i;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__imm_s;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__imm_b;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__imm_j;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__alu_result;
        IData/*31:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__next_pc;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v0;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v1;
        IData/*31:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v1;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v2;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v3;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v4;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v5;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v6;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v7;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v8;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v9;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v10;
        IData/*31:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v10;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v11;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v12;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans__v13;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v0;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v1;
    };
    struct {
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v2;
        IData/*31:0*/ __Vdlyvlsb__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v3;
        IData/*17:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__active_row__v0;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_wdata;
        QData/*63:0*/ tb_cva6_minimal_top__DOT__dut__DOT__axi_rdata;
        QData/*63:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmd_wr_data;
        QData/*63:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdmngr_to_cmdprocessor_cmd_data;
        QData/*63:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__cmdprocessor_to_cmdmngr_read_data;
        QData/*63:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__dfi_to_cmdpr_rddata;
        VlWide<8>/*229:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__wr_trans;
        QData/*63:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__command_packet;
        VlWide<15>/*455:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__cmd_queue;
        QData/*56:0*/ tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT____Vlvbound_h409d9cb8__0;
        QData/*63:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf__v2;
        QData/*63:0*/ __Vdlyvval__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue__v0;
        VlWide<15>/*455:0*/ __Vdly__tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_dfi_interface__DOT__cmd_queue;
        VlUnpacked<IData/*31:0*/, 1024> tb_cva6_minimal_top__DOT__hbm3_loopback_mem;
        VlUnpacked<IData/*31:0*/, 11> tb_cva6_minimal_top__DOT__prev_regs;
        VlUnpacked<IData/*31:0*/, 256> tb_cva6_minimal_top__DOT__dut__DOT__u_boot_rom__DOT__rom;
        VlUnpacked<IData/*31:0*/, 1024> tb_cva6_minimal_top__DOT__dut__DOT__u_data_ram__DOT__ram;
        VlUnpacked<CData/*7:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_uart_debug__DOT__fifo_mem;
        VlUnpacked<CData/*1:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__ch_state_stub;
        VlUnpacked<CData/*3:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__ch_active_banks_stub;
        VlUnpacked<IData/*31:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__ch_read_count_stub;
        VlUnpacked<IData/*31:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__ch_write_count_stub;
        VlUnpacked<CData/*0:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_ch_en;
        VlUnpacked<CData/*0:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_ch_train_en;
        VlUnpacked<CData/*0:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_apb_slave__DOT__reg_ch_pseudo_ch_en;
        VlUnpacked<VlWide<8>/*229:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_trans;
        VlUnpacked<VlWide<3>/*69:0*/, 8> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_axi_slave__DOT__rd_data_buf;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__cmd_queue;
        VlUnpacked<CData/*2:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_current_bit_idx;
        VlUnpacked<CData/*7:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_remaining_bits;
        VlUnpacked<CData/*2:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_bank_addr;
        VlUnpacked<CData/*7:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_burst_len;
        VlUnpacked<SData/*15:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_row_addr;
        VlUnpacked<SData/*9:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_col_addr;
        VlUnpacked<QData/*63:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_write_data;
        VlUnpacked<CData/*7:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_age_counter;
        VlUnpacked<CData/*3:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_channel;
        VlUnpacked<CData/*1:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_bank_group;
        VlUnpacked<CData/*7:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__queue_cmd_id;
        VlUnpacked<CData/*7:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_cmd_type;
        VlUnpacked<CData/*2:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_bank;
        VlUnpacked<SData/*15:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_row;
        VlUnpacked<SData/*9:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_col;
        VlUnpacked<CData/*7:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_burst_len;
        VlUnpacked<QData/*63:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_write_data;
        VlUnpacked<CData/*3:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_channel;
        VlUnpacked<CData/*1:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_bank_group;
        VlUnpacked<CData/*7:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__decoded_cmd_id;
        VlUnpacked<QData/*63:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_command_manager__DOT__rd_queue;
        VlUnpacked<VlUnpacked<VlUnpacked<VlWide<5>/*136:0*/, 1024>, 8192>, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__memory_array;
        VlUnpacked<IData/*17:0*/, 16> tb_cva6_minimal_top__DOT__dut__DOT__u_hbm3_controller__DOT__u_hbm3_phy__DOT__active_row;
        VlUnpacked<IData/*31:0*/, 32> tb_cva6_minimal_top__DOT__dut__DOT__u_riscv_core__DOT__regs;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h7794db06__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_cva6_minimal_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_cva6_minimal_top___024root(Vtb_cva6_minimal_top__Syms* symsp, const char* v__name);
    ~Vtb_cva6_minimal_top___024root();
    VL_UNCOPYABLE(Vtb_cva6_minimal_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
